using System.Globalization;

namespace OnlyWinget;

public static class TextResources
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Nav_Dashboard"] = "Dashboard",
        ["Nav_Presets"] = "Presets",
        ["Nav_Search"] = "Search",
        ["Nav_Updates"] = "Updates",
        ["Nav_Sources"] = "Sources",
        ["Nav_Activity"] = "Activity",
        ["Dashboard_Title"] = "Overview",
        ["Dashboard_Winget"] = "winget",
        ["Dashboard_Presets"] = "Presets",
        ["Dashboard_SearchResults"] = "Search results",
        ["Dashboard_Updates"] = "Updates",
        ["Dashboard_Sources"] = "Sources",
        ["Dashboard_RecentActivity"] = "Recent activity",
        ["Dashboard_Winget_Available"] = "Available",
        ["Dashboard_Winget_Unavailable"] = "Not available",
        ["Dashboard_Winget_Unknown"] = "Checking",
        ["Presets_Title"] = "Presets",
        ["Preset_Name"] = "Preset name",
        ["Package_Id"] = "Package id",
        ["Package_Source"] = "Source",
        ["Source_Name"] = "Source name",
        ["Source_Argument"] = "Source URL or argument",
        ["Source_Status_Available"] = "Available",
        ["Source_Status_Unavailable"] = "Unavailable",
        ["Source_Status_Unknown"] = "Unknown",
        ["Import_Json"] = "Import JSON",
        ["Export_Json"] = "Export JSON",
        ["Search_Query"] = "Search winget packages",
        ["Updates_Title"] = "Updates",
        ["Sources_Title"] = "Sources",
        ["Activity_Title"] = "Activity",
        ["Empty_Presets"] = "Create or import a preset to start.",
        ["Empty_Packages"] = "No packages in the active preset.",
        ["Empty_Search"] = "Search results will appear here.",
        ["Empty_Updates"] = "Refresh updates to review available upgrades.",
        ["Empty_Sources"] = "Refresh sources to inspect winget repositories.",
        ["Empty_Activity"] = "No activity yet.",
        ["Command_Preset_Add"] = "Add preset",
        ["Command_Preset_Rename"] = "Rename",
        ["Command_Preset_Remove"] = "Remove preset",
        ["Command_PresetPackage_Add"] = "Add package",
        ["Command_PresetPackage_Edit"] = "Edit package",
        ["Command_PresetPackage_Remove"] = "Remove selected",
        ["Command_Preset_Import"] = "Import",
        ["Command_Preset_Export"] = "Export",
        ["Command_Workspace_Save"] = "Save workspace",
        ["Command_Preset_ApplyInstall"] = "Install preset",
        ["Command_Preset_ApplyUninstall"] = "Uninstall preset",
        ["Command_Search_Execute"] = "Search",
        ["Command_Search_AddSelected"] = "Add selected",
        ["Command_Updates_Refresh"] = "Refresh",
        ["Command_Updates_ApplySelected"] = "Apply selected",
        ["Command_Sources_Refresh"] = "Refresh",
        ["Command_Sources_Update"] = "Update DB",
        ["Command_Sources_Add"] = "Add source",
        ["Command_Sources_Remove"] = "Remove selected",
        ["Command_Sources_Reset"] = "Reset defaults",
        ["Command_Operation_Cancel"] = "Cancel",
        ["Command_Select_All"] = "Select all",
        ["Command_Activity_Clear"] = "Clear",
        ["Dialog_RemoveSource_Title"] = "Remove source",
        ["Dialog_RemoveSource_Message"] = "Remove the selected winget source?",
        ["Dialog_ResetSources_Title"] = "Reset sources",
        ["Dialog_ResetSources_Message"] = "Reset winget sources to defaults?",
        ["Dialog_Confirm"] = "Confirm",
        ["Dialog_Cancel"] = "Cancel"
    };

    private static readonly IReadOnlyDictionary<string, string> Italian = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Nav_Dashboard"] = "Dashboard",
        ["Nav_Presets"] = "Preset",
        ["Nav_Search"] = "Cerca",
        ["Nav_Updates"] = "Aggiornamenti",
        ["Nav_Sources"] = "Sorgenti",
        ["Nav_Activity"] = "Attivita",
        ["Dashboard_Title"] = "Panoramica",
        ["Dashboard_Winget"] = "winget",
        ["Dashboard_Presets"] = "Preset",
        ["Dashboard_SearchResults"] = "Risultati ricerca",
        ["Dashboard_Updates"] = "Aggiornamenti",
        ["Dashboard_Sources"] = "Sorgenti",
        ["Dashboard_RecentActivity"] = "Attivita recente",
        ["Dashboard_Winget_Available"] = "Disponibile",
        ["Dashboard_Winget_Unavailable"] = "Non disponibile",
        ["Dashboard_Winget_Unknown"] = "Verifica",
        ["Presets_Title"] = "Preset",
        ["Preset_Name"] = "Nome preset",
        ["Package_Id"] = "ID pacchetto",
        ["Package_Source"] = "Origine",
        ["Source_Name"] = "Nome sorgente",
        ["Source_Argument"] = "URL o argomento sorgente",
        ["Source_Status_Available"] = "Disponibile",
        ["Source_Status_Unavailable"] = "Non disponibile",
        ["Source_Status_Unknown"] = "Sconosciuto",
        ["Import_Json"] = "JSON importazione",
        ["Export_Json"] = "JSON esportazione",
        ["Search_Query"] = "Cerca pacchetti winget",
        ["Updates_Title"] = "Aggiornamenti",
        ["Sources_Title"] = "Sorgenti",
        ["Activity_Title"] = "Attivita",
        ["Empty_Presets"] = "Crea o importa un preset per iniziare.",
        ["Empty_Packages"] = "Nessun pacchetto nel preset attivo.",
        ["Empty_Search"] = "I risultati della ricerca appariranno qui.",
        ["Empty_Updates"] = "Aggiorna l'elenco per vedere gli upgrade disponibili.",
        ["Empty_Sources"] = "Aggiorna le sorgenti per controllare i repository winget.",
        ["Empty_Activity"] = "Nessuna attivita.",
        ["Command_Preset_Add"] = "Aggiungi preset",
        ["Command_Preset_Rename"] = "Rinomina",
        ["Command_Preset_Remove"] = "Rimuovi preset",
        ["Command_PresetPackage_Add"] = "Aggiungi pacchetto",
        ["Command_PresetPackage_Edit"] = "Modifica pacchetto",
        ["Command_PresetPackage_Remove"] = "Rimuovi selezionati",
        ["Command_Preset_Import"] = "Importa",
        ["Command_Preset_Export"] = "Esporta",
        ["Command_Workspace_Save"] = "Salva workspace",
        ["Command_Preset_ApplyInstall"] = "Installa preset",
        ["Command_Preset_ApplyUninstall"] = "Disinstalla preset",
        ["Command_Search_Execute"] = "Cerca",
        ["Command_Search_AddSelected"] = "Aggiungi selezionati",
        ["Command_Updates_Refresh"] = "Aggiorna",
        ["Command_Updates_ApplySelected"] = "Applica selezionati",
        ["Command_Sources_Refresh"] = "Aggiorna",
        ["Command_Sources_Update"] = "Aggiorna DB",
        ["Command_Sources_Add"] = "Aggiungi sorgente",
        ["Command_Sources_Remove"] = "Rimuovi selezionata",
        ["Command_Sources_Reset"] = "Ripristina default",
        ["Command_Operation_Cancel"] = "Annulla",
        ["Command_Select_All"] = "Seleziona tutto",
        ["Command_Activity_Clear"] = "Svuota",
        ["Dialog_RemoveSource_Title"] = "Rimuovi sorgente",
        ["Dialog_RemoveSource_Message"] = "Rimuovere la sorgente winget selezionata?",
        ["Dialog_ResetSources_Title"] = "Ripristina sorgenti",
        ["Dialog_ResetSources_Message"] = "Ripristinare le sorgenti winget predefinite?",
        ["Dialog_Confirm"] = "Conferma",
        ["Dialog_Cancel"] = "Annulla"
    };

    public static string Get(string key)
    {
        var resources = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("it", StringComparison.OrdinalIgnoreCase)
            ? Italian
            : English;
        return resources.TryGetValue(key, out var value) ? value : key;
    }
}
