// OnlyWinget
// Copyright (c) 2026 Danny Perondi. All rights reserved.
// Proprietary and confidential. Unauthorized copying, modification,
// distribution, sublicensing, or commercial use is prohibited.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace OnlyWinget.Services;

public static class WingetKnownErrorCatalog
{
    // Synchronized from microsoft/winget-cli master:
    // src/AppInstallerSharedLib/Public/AppInstallerErrors.h
    private static readonly IReadOnlyDictionary<int, string> Symbols = new Dictionary<int, string>
    {
        [unchecked((int)0x0A150202)] = "WINGET_INSTALLED_STATUS_INSTALL_LOCATION_NOT_APPLICABLE",
        [unchecked((int)0x0A150206)] = "WINGET_INSTALLED_STATUS_FILE_FOUND_WITHOUT_HASH_CHECK",
        [unchecked((int)0x8A150001)] = "APPINSTALLER_CLI_ERROR_INTERNAL_ERROR",
        [unchecked((int)0x8A150002)] = "APPINSTALLER_CLI_ERROR_INVALID_CL_ARGUMENTS",
        [unchecked((int)0x8A150003)] = "APPINSTALLER_CLI_ERROR_COMMAND_FAILED",
        [unchecked((int)0x8A150004)] = "APPINSTALLER_CLI_ERROR_MANIFEST_FAILED",
        [unchecked((int)0x8A150005)] = "APPINSTALLER_CLI_ERROR_CTRL_SIGNAL_RECEIVED",
        [unchecked((int)0x8A150006)] = "APPINSTALLER_CLI_ERROR_SHELLEXEC_INSTALL_FAILED",
        [unchecked((int)0x8A150007)] = "APPINSTALLER_CLI_ERROR_UNSUPPORTED_MANIFESTVERSION",
        [unchecked((int)0x8A150008)] = "APPINSTALLER_CLI_ERROR_DOWNLOAD_FAILED",
        [unchecked((int)0x8A150009)] = "APPINSTALLER_CLI_ERROR_CANNOT_WRITE_TO_UPLEVEL_INDEX",
        [unchecked((int)0x8A15000A)] = "APPINSTALLER_CLI_ERROR_INDEX_INTEGRITY_COMPROMISED",
        [unchecked((int)0x8A15000B)] = "APPINSTALLER_CLI_ERROR_SOURCES_INVALID",
        [unchecked((int)0x8A15000C)] = "APPINSTALLER_CLI_ERROR_SOURCE_NAME_ALREADY_EXISTS",
        [unchecked((int)0x8A15000D)] = "APPINSTALLER_CLI_ERROR_INVALID_SOURCE_TYPE",
        [unchecked((int)0x8A15000E)] = "APPINSTALLER_CLI_ERROR_PACKAGE_IS_BUNDLE",
        [unchecked((int)0x8A15000F)] = "APPINSTALLER_CLI_ERROR_SOURCE_DATA_MISSING",
        [unchecked((int)0x8A150010)] = "APPINSTALLER_CLI_ERROR_NO_APPLICABLE_INSTALLER",
        [unchecked((int)0x8A150011)] = "APPINSTALLER_CLI_ERROR_INSTALLER_HASH_MISMATCH",
        [unchecked((int)0x8A150012)] = "APPINSTALLER_CLI_ERROR_SOURCE_NAME_DOES_NOT_EXIST",
        [unchecked((int)0x8A150013)] = "APPINSTALLER_CLI_ERROR_SOURCE_ARG_ALREADY_EXISTS",
        [unchecked((int)0x8A150014)] = "APPINSTALLER_CLI_ERROR_NO_APPLICATIONS_FOUND",
        [unchecked((int)0x8A150015)] = "APPINSTALLER_CLI_ERROR_NO_SOURCES_DEFINED",
        [unchecked((int)0x8A150016)] = "APPINSTALLER_CLI_ERROR_MULTIPLE_APPLICATIONS_FOUND",
        [unchecked((int)0x8A150017)] = "APPINSTALLER_CLI_ERROR_NO_MANIFEST_FOUND",
        [unchecked((int)0x8A150018)] = "APPINSTALLER_CLI_ERROR_EXTENSION_PUBLIC_FAILED",
        [unchecked((int)0x8A150019)] = "APPINSTALLER_CLI_ERROR_COMMAND_REQUIRES_ADMIN",
        [unchecked((int)0x8A15001A)] = "APPINSTALLER_CLI_ERROR_SOURCE_NOT_SECURE",
        [unchecked((int)0x8A15001B)] = "APPINSTALLER_CLI_ERROR_MSSTORE_BLOCKED_BY_POLICY",
        [unchecked((int)0x8A15001C)] = "APPINSTALLER_CLI_ERROR_MSSTORE_APP_BLOCKED_BY_POLICY",
        [unchecked((int)0x8A15001D)] = "APPINSTALLER_CLI_ERROR_EXPERIMENTAL_FEATURE_DISABLED",
        [unchecked((int)0x8A15001E)] = "APPINSTALLER_CLI_ERROR_MSSTORE_INSTALL_FAILED",
        [unchecked((int)0x8A15001F)] = "APPINSTALLER_CLI_ERROR_COMPLETE_INPUT_BAD",
        [unchecked((int)0x8A150020)] = "APPINSTALLER_CLI_ERROR_YAML_INIT_FAILED",
        [unchecked((int)0x8A150021)] = "APPINSTALLER_CLI_ERROR_YAML_INVALID_MAPPING_KEY",
        [unchecked((int)0x8A150022)] = "APPINSTALLER_CLI_ERROR_YAML_DUPLICATE_MAPPING_KEY",
        [unchecked((int)0x8A150023)] = "APPINSTALLER_CLI_ERROR_YAML_INVALID_OPERATION",
        [unchecked((int)0x8A150024)] = "APPINSTALLER_CLI_ERROR_YAML_DOC_BUILD_FAILED",
        [unchecked((int)0x8A150025)] = "APPINSTALLER_CLI_ERROR_YAML_INVALID_EMITTER_STATE",
        [unchecked((int)0x8A150026)] = "APPINSTALLER_CLI_ERROR_YAML_INVALID_DATA",
        [unchecked((int)0x8A150027)] = "APPINSTALLER_CLI_ERROR_LIBYAML_ERROR",
        [unchecked((int)0x8A150028)] = "APPINSTALLER_CLI_ERROR_MANIFEST_VALIDATION_WARNING",
        [unchecked((int)0x8A150029)] = "APPINSTALLER_CLI_ERROR_MANIFEST_VALIDATION_FAILURE",
        [unchecked((int)0x8A15002A)] = "APPINSTALLER_CLI_ERROR_INVALID_MANIFEST",
        [unchecked((int)0x8A15002B)] = "APPINSTALLER_CLI_ERROR_UPDATE_NOT_APPLICABLE",
        [unchecked((int)0x8A15002C)] = "APPINSTALLER_CLI_ERROR_UPDATE_ALL_HAS_FAILURE",
        [unchecked((int)0x8A15002D)] = "APPINSTALLER_CLI_ERROR_INSTALLER_SECURITY_CHECK_FAILED",
        [unchecked((int)0x8A15002E)] = "APPINSTALLER_CLI_ERROR_DOWNLOAD_SIZE_MISMATCH",
        [unchecked((int)0x8A15002F)] = "APPINSTALLER_CLI_ERROR_NO_UNINSTALL_INFO_FOUND",
        [unchecked((int)0x8A150030)] = "APPINSTALLER_CLI_ERROR_EXEC_UNINSTALL_COMMAND_FAILED",
        [unchecked((int)0x8A150031)] = "APPINSTALLER_CLI_ERROR_ICU_BREAK_ITERATOR_ERROR",
        [unchecked((int)0x8A150032)] = "APPINSTALLER_CLI_ERROR_ICU_CASEMAP_ERROR",
        [unchecked((int)0x8A150033)] = "APPINSTALLER_CLI_ERROR_ICU_REGEX_ERROR",
        [unchecked((int)0x8A150034)] = "APPINSTALLER_CLI_ERROR_IMPORT_INSTALL_FAILED",
        [unchecked((int)0x8A150035)] = "APPINSTALLER_CLI_ERROR_NOT_ALL_PACKAGES_FOUND",
        [unchecked((int)0x8A150036)] = "APPINSTALLER_CLI_ERROR_JSON_INVALID_FILE",
        [unchecked((int)0x8A150037)] = "APPINSTALLER_CLI_ERROR_SOURCE_NOT_REMOTE",
        [unchecked((int)0x8A150038)] = "APPINSTALLER_CLI_ERROR_UNSUPPORTED_RESTSOURCE",
        [unchecked((int)0x8A150039)] = "APPINSTALLER_CLI_ERROR_RESTSOURCE_INVALID_DATA",
        [unchecked((int)0x8A15003A)] = "APPINSTALLER_CLI_ERROR_BLOCKED_BY_POLICY",
        [unchecked((int)0x8A15003B)] = "APPINSTALLER_CLI_ERROR_RESTAPI_INTERNAL_ERROR",
        [unchecked((int)0x8A15003C)] = "APPINSTALLER_CLI_ERROR_RESTSOURCE_INVALID_URL",
        [unchecked((int)0x8A15003D)] = "APPINSTALLER_CLI_ERROR_RESTAPI_UNSUPPORTED_MIME_TYPE",
        [unchecked((int)0x8A15003E)] = "APPINSTALLER_CLI_ERROR_RESTSOURCE_INVALID_VERSION",
        [unchecked((int)0x8A15003F)] = "APPINSTALLER_CLI_ERROR_SOURCE_DATA_INTEGRITY_FAILURE",
        [unchecked((int)0x8A150040)] = "APPINSTALLER_CLI_ERROR_STREAM_READ_FAILURE",
        [unchecked((int)0x8A150041)] = "APPINSTALLER_CLI_ERROR_PACKAGE_AGREEMENTS_NOT_ACCEPTED",
        [unchecked((int)0x8A150042)] = "APPINSTALLER_CLI_ERROR_PROMPT_INPUT_ERROR",
        [unchecked((int)0x8A150043)] = "APPINSTALLER_CLI_ERROR_UNSUPPORTED_SOURCE_REQUEST",
        [unchecked((int)0x8A150044)] = "APPINSTALLER_CLI_ERROR_RESTAPI_ENDPOINT_NOT_FOUND",
        [unchecked((int)0x8A150045)] = "APPINSTALLER_CLI_ERROR_SOURCE_OPEN_FAILED",
        [unchecked((int)0x8A150046)] = "APPINSTALLER_CLI_ERROR_SOURCE_AGREEMENTS_NOT_ACCEPTED",
        [unchecked((int)0x8A150047)] = "APPINSTALLER_CLI_ERROR_CUSTOMHEADER_EXCEEDS_MAXLENGTH",
        [unchecked((int)0x8A150048)] = "APPINSTALLER_CLI_ERROR_MISSING_RESOURCE_FILE",
        [unchecked((int)0x8A150049)] = "APPINSTALLER_CLI_ERROR_MSI_INSTALL_FAILED",
        [unchecked((int)0x8A15004A)] = "APPINSTALLER_CLI_ERROR_INVALID_MSIEXEC_ARGUMENT",
        [unchecked((int)0x8A15004B)] = "APPINSTALLER_CLI_ERROR_FAILED_TO_OPEN_ALL_SOURCES",
        [unchecked((int)0x8A15004C)] = "APPINSTALLER_CLI_ERROR_DEPENDENCIES_VALIDATION_FAILED",
        [unchecked((int)0x8A15004D)] = "APPINSTALLER_CLI_ERROR_MISSING_PACKAGE",
        [unchecked((int)0x8A15004E)] = "APPINSTALLER_CLI_ERROR_INVALID_TABLE_COLUMN",
        [unchecked((int)0x8A15004F)] = "APPINSTALLER_CLI_ERROR_UPGRADE_VERSION_NOT_NEWER",
        [unchecked((int)0x8A150050)] = "APPINSTALLER_CLI_ERROR_UPGRADE_VERSION_UNKNOWN",
        [unchecked((int)0x8A150051)] = "APPINSTALLER_CLI_ERROR_ICU_CONVERSION_ERROR",
        [unchecked((int)0x8A150052)] = "APPINSTALLER_CLI_ERROR_PORTABLE_INSTALL_FAILED",
        [unchecked((int)0x8A150053)] = "APPINSTALLER_CLI_ERROR_PORTABLE_REPARSE_POINT_NOT_SUPPORTED",
        [unchecked((int)0x8A150054)] = "APPINSTALLER_CLI_ERROR_PORTABLE_PACKAGE_ALREADY_EXISTS",
        [unchecked((int)0x8A150055)] = "APPINSTALLER_CLI_ERROR_PORTABLE_SYMLINK_PATH_IS_DIRECTORY",
        [unchecked((int)0x8A150056)] = "APPINSTALLER_CLI_ERROR_INSTALLER_PROHIBITS_ELEVATION",
        [unchecked((int)0x8A150057)] = "APPINSTALLER_CLI_ERROR_PORTABLE_UNINSTALL_FAILED",
        [unchecked((int)0x8A150058)] = "APPINSTALLER_CLI_ERROR_ARP_VERSION_VALIDATION_FAILED",
        [unchecked((int)0x8A150059)] = "APPINSTALLER_CLI_ERROR_UNSUPPORTED_ARGUMENT",
        [unchecked((int)0x8A15005A)] = "APPINSTALLER_CLI_ERROR_BIND_WITH_EMBEDDED_NULL",
        [unchecked((int)0x8A15005B)] = "APPINSTALLER_CLI_ERROR_NESTEDINSTALLER_NOT_FOUND",
        [unchecked((int)0x8A15005C)] = "APPINSTALLER_CLI_ERROR_EXTRACT_ARCHIVE_FAILED",
        [unchecked((int)0x8A15005D)] = "APPINSTALLER_CLI_ERROR_NESTEDINSTALLER_INVALID_PATH",
        [unchecked((int)0x8A15005E)] = "APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH",
        [unchecked((int)0x8A15005F)] = "APPINSTALLER_CLI_ERROR_INSTALL_LOCATION_REQUIRED",
        [unchecked((int)0x8A150060)] = "APPINSTALLER_CLI_ERROR_ARCHIVE_SCAN_FAILED",
        [unchecked((int)0x8A150061)] = "APPINSTALLER_CLI_ERROR_PACKAGE_ALREADY_INSTALLED",
        [unchecked((int)0x8A150062)] = "APPINSTALLER_CLI_ERROR_PIN_ALREADY_EXISTS",
        [unchecked((int)0x8A150063)] = "APPINSTALLER_CLI_ERROR_PIN_DOES_NOT_EXIST",
        [unchecked((int)0x8A150064)] = "APPINSTALLER_CLI_ERROR_CANNOT_OPEN_PINNING_INDEX",
        [unchecked((int)0x8A150065)] = "APPINSTALLER_CLI_ERROR_MULTIPLE_INSTALL_FAILED",
        [unchecked((int)0x8A150066)] = "APPINSTALLER_CLI_ERROR_MULTIPLE_UNINSTALL_FAILED",
        [unchecked((int)0x8A150067)] = "APPINSTALLER_CLI_ERROR_NOT_ALL_QUERIES_FOUND_SINGLE",
        [unchecked((int)0x8A150068)] = "APPINSTALLER_CLI_ERROR_PACKAGE_IS_PINNED",
        [unchecked((int)0x8A150069)] = "APPINSTALLER_CLI_ERROR_PACKAGE_IS_STUB",
        [unchecked((int)0x8A15006A)] = "APPINSTALLER_CLI_ERROR_APPTERMINATION_RECEIVED",
        [unchecked((int)0x8A15006B)] = "APPINSTALLER_CLI_ERROR_DOWNLOAD_DEPENDENCIES",
        [unchecked((int)0x8A15006C)] = "APPINSTALLER_CLI_ERROR_DOWNLOAD_COMMAND_PROHIBITED",
        [unchecked((int)0x8A15006D)] = "APPINSTALLER_CLI_ERROR_SERVICE_UNAVAILABLE",
        [unchecked((int)0x8A15006E)] = "APPINSTALLER_CLI_ERROR_RESUME_ID_NOT_FOUND",
        [unchecked((int)0x8A15006F)] = "APPINSTALLER_CLI_ERROR_CLIENT_VERSION_MISMATCH",
        [unchecked((int)0x8A150070)] = "APPINSTALLER_CLI_ERROR_INVALID_RESUME_STATE",
        [unchecked((int)0x8A150071)] = "APPINSTALLER_CLI_ERROR_CANNOT_OPEN_CHECKPOINT_INDEX",
        [unchecked((int)0x8A150072)] = "APPINSTALLER_CLI_ERROR_RESUME_LIMIT_EXCEEDED",
        [unchecked((int)0x8A150073)] = "APPINSTALLER_CLI_ERROR_INVALID_AUTHENTICATION_INFO",
        [unchecked((int)0x8A150074)] = "APPINSTALLER_CLI_ERROR_AUTHENTICATION_TYPE_NOT_SUPPORTED",
        [unchecked((int)0x8A150075)] = "APPINSTALLER_CLI_ERROR_AUTHENTICATION_FAILED",
        [unchecked((int)0x8A150076)] = "APPINSTALLER_CLI_ERROR_AUTHENTICATION_INTERACTIVE_REQUIRED",
        [unchecked((int)0x8A150077)] = "APPINSTALLER_CLI_ERROR_AUTHENTICATION_CANCELLED_BY_USER",
        [unchecked((int)0x8A150078)] = "APPINSTALLER_CLI_ERROR_AUTHENTICATION_INCORRECT_ACCOUNT",
        [unchecked((int)0x8A150079)] = "APPINSTALLER_CLI_ERROR_NO_REPAIR_INFO_FOUND",
        [unchecked((int)0x8A15007A)] = "APPINSTALLER_CLI_ERROR_REPAIR_NOT_APPLICABLE",
        [unchecked((int)0x8A15007B)] = "APPINSTALLER_CLI_ERROR_EXEC_REPAIR_FAILED",
        [unchecked((int)0x8A15007C)] = "APPINSTALLER_CLI_ERROR_REPAIR_NOT_SUPPORTED",
        [unchecked((int)0x8A15007D)] = "APPINSTALLER_CLI_ERROR_ADMIN_CONTEXT_REPAIR_PROHIBITED",
        [unchecked((int)0x8A15007E)] = "APPINSTALLER_CLI_ERROR_SQLITE_CONNECTION_TERMINATED",
        [unchecked((int)0x8A15007F)] = "APPINSTALLER_CLI_ERROR_DISPLAYCATALOG_API_FAILED",
        [unchecked((int)0x8A150080)] = "APPINSTALLER_CLI_ERROR_NO_APPLICABLE_DISPLAYCATALOG_PACKAGE",
        [unchecked((int)0x8A150081)] = "APPINSTALLER_CLI_ERROR_SFSCLIENT_API_FAILED",
        [unchecked((int)0x8A150082)] = "APPINSTALLER_CLI_ERROR_NO_APPLICABLE_SFSCLIENT_PACKAGE",
        [unchecked((int)0x8A150083)] = "APPINSTALLER_CLI_ERROR_LICENSING_API_FAILED",
        [unchecked((int)0x8A150084)] = "APPINSTALLER_CLI_ERROR_SFSCLIENT_PACKAGE_NOT_SUPPORTED",
        [unchecked((int)0x8A150085)] = "APPINSTALLER_CLI_ERROR_LICENSING_API_FAILED_FORBIDDEN",
        [unchecked((int)0x8A150086)] = "APPINSTALLER_CLI_ERROR_INSTALLER_ZERO_BYTE_FILE",
        [unchecked((int)0x8A150087)] = "APPINSTALLER_CLI_ERROR_FONT_INSTALL_FAILED",
        [unchecked((int)0x8A150088)] = "APPINSTALLER_CLI_ERROR_FONT_FILE_NOT_SUPPORTED",
        [unchecked((int)0x8A150089)] = "APPINSTALLER_CLI_ERROR_FONT_ALREADY_INSTALLED",
        [unchecked((int)0x8A15008A)] = "APPINSTALLER_CLI_ERROR_FONT_FILE_NOT_FOUND",
        [unchecked((int)0x8A15008B)] = "APPINSTALLER_CLI_ERROR_FONT_UNINSTALL_FAILED",
        [unchecked((int)0x8A15008C)] = "APPINSTALLER_CLI_ERROR_FONT_VALIDATION_FAILED",
        [unchecked((int)0x8A15008D)] = "APPINSTALLER_CLI_ERROR_FONT_ROLLBACK_FAILED",
        [unchecked((int)0x8A15008E)] = "APPINSTALLER_CLI_ERROR_UPDATE_INSTALL_TECHNOLOGY_MISMATCH",
        [unchecked((int)0x8A150101)] = "APPINSTALLER_CLI_ERROR_INSTALL_PACKAGE_IN_USE",
        [unchecked((int)0x8A150102)] = "APPINSTALLER_CLI_ERROR_INSTALL_INSTALL_IN_PROGRESS",
        [unchecked((int)0x8A150103)] = "APPINSTALLER_CLI_ERROR_INSTALL_FILE_IN_USE",
        [unchecked((int)0x8A150104)] = "APPINSTALLER_CLI_ERROR_INSTALL_MISSING_DEPENDENCY",
        [unchecked((int)0x8A150105)] = "APPINSTALLER_CLI_ERROR_INSTALL_DISK_FULL",
        [unchecked((int)0x8A150106)] = "APPINSTALLER_CLI_ERROR_INSTALL_INSUFFICIENT_MEMORY",
        [unchecked((int)0x8A150107)] = "APPINSTALLER_CLI_ERROR_INSTALL_NO_NETWORK",
        [unchecked((int)0x8A150108)] = "APPINSTALLER_CLI_ERROR_INSTALL_CONTACT_SUPPORT",
        [unchecked((int)0x8A150109)] = "APPINSTALLER_CLI_ERROR_INSTALL_REBOOT_REQUIRED_TO_FINISH",
        [unchecked((int)0x8A15010A)] = "APPINSTALLER_CLI_ERROR_INSTALL_REBOOT_REQUIRED_FOR_INSTALL",
        [unchecked((int)0x8A15010B)] = "APPINSTALLER_CLI_ERROR_INSTALL_REBOOT_INITIATED",
        [unchecked((int)0x8A15010C)] = "APPINSTALLER_CLI_ERROR_INSTALL_CANCELLED_BY_USER",
        [unchecked((int)0x8A15010D)] = "APPINSTALLER_CLI_ERROR_INSTALL_ALREADY_INSTALLED",
        [unchecked((int)0x8A15010E)] = "APPINSTALLER_CLI_ERROR_INSTALL_DOWNGRADE",
        [unchecked((int)0x8A15010F)] = "APPINSTALLER_CLI_ERROR_INSTALL_BLOCKED_BY_POLICY",
        [unchecked((int)0x8A150110)] = "APPINSTALLER_CLI_ERROR_INSTALL_DEPENDENCIES",
        [unchecked((int)0x8A150111)] = "APPINSTALLER_CLI_ERROR_INSTALL_PACKAGE_IN_USE_BY_APPLICATION",
        [unchecked((int)0x8A150112)] = "APPINSTALLER_CLI_ERROR_INSTALL_INVALID_PARAMETER",
        [unchecked((int)0x8A150113)] = "APPINSTALLER_CLI_ERROR_INSTALL_SYSTEM_NOT_SUPPORTED",
        [unchecked((int)0x8A150114)] = "APPINSTALLER_CLI_ERROR_INSTALL_UPGRADE_NOT_SUPPORTED",
        [unchecked((int)0x8A150115)] = "APPINSTALLER_CLI_ERROR_INSTALL_CUSTOM_ERROR",
        [unchecked((int)0x8A150201)] = "WINGET_INSTALLED_STATUS_ARP_ENTRY_NOT_FOUND",
        [unchecked((int)0x8A150203)] = "WINGET_INSTALLED_STATUS_INSTALL_LOCATION_NOT_FOUND",
        [unchecked((int)0x8A150204)] = "WINGET_INSTALLED_STATUS_FILE_HASH_MISMATCH",
        [unchecked((int)0x8A150205)] = "WINGET_INSTALLED_STATUS_FILE_NOT_FOUND",
        [unchecked((int)0x8A150207)] = "WINGET_INSTALLED_STATUS_FILE_ACCESS_ERROR",
        [unchecked((int)0x8A15C001)] = "WINGET_CONFIG_ERROR_INVALID_CONFIGURATION_FILE",
        [unchecked((int)0x8A15C002)] = "WINGET_CONFIG_ERROR_INVALID_YAML",
        [unchecked((int)0x8A15C003)] = "WINGET_CONFIG_ERROR_INVALID_FIELD_TYPE",
        [unchecked((int)0x8A15C004)] = "WINGET_CONFIG_ERROR_UNKNOWN_CONFIGURATION_FILE_VERSION",
        [unchecked((int)0x8A15C005)] = "WINGET_CONFIG_ERROR_SET_APPLY_FAILED",
        [unchecked((int)0x8A15C006)] = "WINGET_CONFIG_ERROR_DUPLICATE_IDENTIFIER",
        [unchecked((int)0x8A15C007)] = "WINGET_CONFIG_ERROR_MISSING_DEPENDENCY",
        [unchecked((int)0x8A15C008)] = "WINGET_CONFIG_ERROR_DEPENDENCY_UNSATISFIED",
        [unchecked((int)0x8A15C009)] = "WINGET_CONFIG_ERROR_ASSERTION_FAILED",
        [unchecked((int)0x8A15C00A)] = "WINGET_CONFIG_ERROR_MANUALLY_SKIPPED",
        [unchecked((int)0x8A15C00B)] = "WINGET_CONFIG_ERROR_WARNING_NOT_ACCEPTED",
        [unchecked((int)0x8A15C00C)] = "WINGET_CONFIG_ERROR_SET_DEPENDENCY_CYCLE",
        [unchecked((int)0x8A15C00D)] = "WINGET_CONFIG_ERROR_INVALID_FIELD_VALUE",
        [unchecked((int)0x8A15C00E)] = "WINGET_CONFIG_ERROR_MISSING_FIELD",
        [unchecked((int)0x8A15C00F)] = "WINGET_CONFIG_ERROR_TEST_FAILED",
        [unchecked((int)0x8A15C010)] = "WINGET_CONFIG_ERROR_TEST_NOT_RUN",
        [unchecked((int)0x8A15C011)] = "WINGET_CONFIG_ERROR_GET_FAILED",
        [unchecked((int)0x8A15C012)] = "WINGET_CONFIG_ERROR_HISTORY_ITEM_NOT_FOUND",
        [unchecked((int)0x8A15C013)] = "WINGET_CONFIG_ERROR_PARAMETER_INTEGRITY_BOUNDARY",
        [unchecked((int)0x8A15C101)] = "WINGET_CONFIG_ERROR_UNIT_NOT_INSTALLED",
        [unchecked((int)0x8A15C102)] = "WINGET_CONFIG_ERROR_UNIT_NOT_FOUND_REPOSITORY",
        [unchecked((int)0x8A15C103)] = "WINGET_CONFIG_ERROR_UNIT_MULTIPLE_MATCHES",
        [unchecked((int)0x8A15C104)] = "WINGET_CONFIG_ERROR_UNIT_INVOKE_GET",
        [unchecked((int)0x8A15C105)] = "WINGET_CONFIG_ERROR_UNIT_INVOKE_TEST",
        [unchecked((int)0x8A15C106)] = "WINGET_CONFIG_ERROR_UNIT_INVOKE_SET",
        [unchecked((int)0x8A15C107)] = "WINGET_CONFIG_ERROR_UNIT_MODULE_CONFLICT",
        [unchecked((int)0x8A15C108)] = "WINGET_CONFIG_ERROR_UNIT_IMPORT_MODULE",
        [unchecked((int)0x8A15C109)] = "WINGET_CONFIG_ERROR_UNIT_INVOKE_INVALID_RESULT",
        [unchecked((int)0x8A15C110)] = "WINGET_CONFIG_ERROR_UNIT_SETTING_CONFIG_ROOT",
        [unchecked((int)0x8A15C111)] = "WINGET_CONFIG_ERROR_UNIT_IMPORT_MODULE_ADMIN",
        [unchecked((int)0x8A15C112)] = "WINGET_CONFIG_ERROR_NOT_SUPPORTED_BY_PROCESSOR",
    };

    // Synchronized from microsoft/winget-cli master:
    // src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
    private static readonly IReadOnlyDictionary<int, string> EnglishDescriptions = new Dictionary<int, string>
    {
        [unchecked((int)0x0A150202)] = "The install location is not applicable.",
        [unchecked((int)0x0A150206)] = "The file was found but the hash was not checked.",
        [unchecked((int)0x8A150001)] = "Internal Error",
        [unchecked((int)0x8A150002)] = "Invalid command line arguments",
        [unchecked((int)0x8A150003)] = "Executing command failed",
        [unchecked((int)0x8A150004)] = "Opening manifest failed",
        [unchecked((int)0x8A150005)] = "Cancellation signal received",
        [unchecked((int)0x8A150006)] = "Running ShellExecute failed",
        [unchecked((int)0x8A150007)] = "Cannot process manifest. The manifest version is higher than supported. Please update the client.",
        [unchecked((int)0x8A150008)] = "Downloading installer failed",
        [unchecked((int)0x8A150009)] = "Cannot write to index; it is a higher schema version",
        [unchecked((int)0x8A15000A)] = "The index is corrupt",
        [unchecked((int)0x8A15000B)] = "The configured source information is corrupt",
        [unchecked((int)0x8A15000C)] = "The source name is already configured",
        [unchecked((int)0x8A15000D)] = "The source type is invalid",
        [unchecked((int)0x8A15000E)] = "The MSIX file is a bundle, not a package",
        [unchecked((int)0x8A15000F)] = "Data required by the source is missing",
        [unchecked((int)0x8A150010)] = "None of the installers are applicable for the current system",
        [unchecked((int)0x8A150011)] = "The installer file's hash does not match the manifest",
        [unchecked((int)0x8A150012)] = "The source name does not exist",
        [unchecked((int)0x8A150013)] = "The source location is already configured under another name",
        [unchecked((int)0x8A150014)] = "No packages found",
        [unchecked((int)0x8A150015)] = "No sources are configured",
        [unchecked((int)0x8A150016)] = "Multiple packages found matching the criteria",
        [unchecked((int)0x8A150017)] = "No manifest found matching the criteria",
        [unchecked((int)0x8A150018)] = "Failed to get Public folder from source package",
        [unchecked((int)0x8A150019)] = "Command requires administrator privileges to run",
        [unchecked((int)0x8A15001A)] = "The source location is not secure",
        [unchecked((int)0x8A15001B)] = "The Microsoft Store client is blocked by policy",
        [unchecked((int)0x8A15001C)] = "The Microsoft Store app is blocked by policy",
        [unchecked((int)0x8A15001D)] = "The feature is currently under development. It can be enabled using `winget settings`.",
        [unchecked((int)0x8A15001E)] = "Failed to install the Microsoft Store app",
        [unchecked((int)0x8A15001F)] = "Failed to perform auto complete",
        [unchecked((int)0x8A150020)] = "Failed to initialize YAML parser",
        [unchecked((int)0x8A150021)] = "Encountered an invalid YAML key",
        [unchecked((int)0x8A150022)] = "Encountered a duplicate YAML key",
        [unchecked((int)0x8A150023)] = "Invalid YAML operation",
        [unchecked((int)0x8A150024)] = "Failed to build YAML doc",
        [unchecked((int)0x8A150025)] = "Invalid YAML emitter state",
        [unchecked((int)0x8A150026)] = "Invalid YAML data",
        [unchecked((int)0x8A150027)] = "LibYAML error",
        [unchecked((int)0x8A150028)] = "Manifest validation succeeded with warning",
        [unchecked((int)0x8A150029)] = "Manifest validation failed",
        [unchecked((int)0x8A15002A)] = "Manifest is invalid",
        [unchecked((int)0x8A15002B)] = "No applicable update found",
        [unchecked((int)0x8A15002C)] = "winget upgrade --all completed with failures",
        [unchecked((int)0x8A15002D)] = "Installer failed security check",
        [unchecked((int)0x8A15002E)] = "Download size does not match expected content length",
        [unchecked((int)0x8A15002F)] = "Uninstall command not found",
        [unchecked((int)0x8A150030)] = "Running uninstall command failed",
        [unchecked((int)0x8A150031)] = "ICU break iterator error",
        [unchecked((int)0x8A150032)] = "ICU casemap error",
        [unchecked((int)0x8A150033)] = "ICU regex error",
        [unchecked((int)0x8A150034)] = "Failed to install one or more imported packages",
        [unchecked((int)0x8A150035)] = "Could not find one or more requested packages",
        [unchecked((int)0x8A150036)] = "Json file is invalid",
        [unchecked((int)0x8A150037)] = "The source location is not remote",
        [unchecked((int)0x8A150038)] = "The configured rest source is not supported",
        [unchecked((int)0x8A150039)] = "Invalid data returned by rest source",
        [unchecked((int)0x8A15003A)] = "Operation is blocked by Group Policy",
        [unchecked((int)0x8A15003B)] = "Rest API internal error",
        [unchecked((int)0x8A15003C)] = "Invalid rest source url",
        [unchecked((int)0x8A15003D)] = "Unsupported MIME type returned by rest API",
        [unchecked((int)0x8A15003E)] = "Invalid rest source contract version",
        [unchecked((int)0x8A15003F)] = "The source data is corrupted or tampered",
        [unchecked((int)0x8A150040)] = "Error reading from the stream",
        [unchecked((int)0x8A150041)] = "Package agreements were not agreed to",
        [unchecked((int)0x8A150042)] = "Error reading input in prompt",
        [unchecked((int)0x8A150043)] = "The search request is not supported by one or more sources",
        [unchecked((int)0x8A150044)] = "The rest API endpoint is not found.",
        [unchecked((int)0x8A150045)] = "Failed to open the source.",
        [unchecked((int)0x8A150046)] = "Source agreements were not agreed to",
        [unchecked((int)0x8A150047)] = "Header size exceeds the allowable limit of 1024 characters. Please reduce the size and try again.",
        [unchecked((int)0x8A150048)] = "Missing resource file",
        [unchecked((int)0x8A150049)] = "Running MSI install failed",
        [unchecked((int)0x8A15004A)] = "Arguments for msiexec are invalid",
        [unchecked((int)0x8A15004B)] = "Failed to open one or more sources",
        [unchecked((int)0x8A15004C)] = "Failed to validate dependencies",
        [unchecked((int)0x8A15004D)] = "One or more package is missing",
        [unchecked((int)0x8A15004E)] = "Invalid table column",
        [unchecked((int)0x8A15004F)] = "The upgrade version is not newer than the installed version",
        [unchecked((int)0x8A150050)] = "Upgrade version is unknown and override is not specified",
        [unchecked((int)0x8A150051)] = "ICU conversion error",
        [unchecked((int)0x8A150052)] = "Failed to install portable package",
        [unchecked((int)0x8A150053)] = "Volume does not support reparse points",
        [unchecked((int)0x8A150054)] = "Portable package from a different source already exists.",
        [unchecked((int)0x8A150055)] = "Unable to create symlink. Path points to a directory.",
        [unchecked((int)0x8A150056)] = "The installer cannot be run from an administrator context.",
        [unchecked((int)0x8A150057)] = "Failed to uninstall portable package",
        [unchecked((int)0x8A150058)] = "Failed to validate DisplayVersion values against index.",
        [unchecked((int)0x8A150059)] = "One or more arguments are not supported.",
        [unchecked((int)0x8A15005A)] = "Embedded null characters are disallowed for SQLite",
        [unchecked((int)0x8A15005B)] = "Failed to find the nested installer in the archive.",
        [unchecked((int)0x8A15005C)] = "Failed to extract archive.",
        [unchecked((int)0x8A15005D)] = "Invalid relative file path to nested installer provided.",
        [unchecked((int)0x8A15005E)] = "The server certificate did not match any of the expected values.",
        [unchecked((int)0x8A15005F)] = "Install location must be provided.",
        [unchecked((int)0x8A150060)] = "Archive malware scan failed.",
        [unchecked((int)0x8A150061)] = "Found at least one version of the package installed.",
        [unchecked((int)0x8A150062)] = "A pin already exists for the package.",
        [unchecked((int)0x8A150063)] = "There is no pin for the package.",
        [unchecked((int)0x8A150064)] = "Unable to open the pin database.",
        [unchecked((int)0x8A150065)] = "One or more applications failed to install",
        [unchecked((int)0x8A150066)] = "One or more applications failed to uninstall",
        [unchecked((int)0x8A150067)] = "One or more queries did not return exactly one match",
        [unchecked((int)0x8A150068)] = "The package has a pin that prevents upgrade.",
        [unchecked((int)0x8A150069)] = "The package currently installed is the stub package",
        [unchecked((int)0x8A15006A)] = "Application shutdown signal received",
        [unchecked((int)0x8A15006B)] = "Failed to download package dependencies.",
        [unchecked((int)0x8A15006C)] = "Failed to download package. Download for offline installation is prohibited.",
        [unchecked((int)0x8A15006D)] = "A required service is busy or unavailable. Try again later.",
        [unchecked((int)0x8A15006E)] = "The guid provided does not correspond to a valid resume state.",
        [unchecked((int)0x8A15006F)] = "The current client version did not match the client version of the saved state.",
        [unchecked((int)0x8A150070)] = "The resume state data is invalid.",
        [unchecked((int)0x8A150071)] = "Unable to open the checkpoint database.",
        [unchecked((int)0x8A150072)] = "Exceeded max resume limit.",
        [unchecked((int)0x8A150073)] = "Invalid authentication info.",
        [unchecked((int)0x8A150074)] = "Authentication method not supported.",
        [unchecked((int)0x8A150075)] = "Authentication failed.",
        [unchecked((int)0x8A150076)] = "Authentication failed. Interactive authentication required.",
        [unchecked((int)0x8A150077)] = "Authentication failed. User cancelled.",
        [unchecked((int)0x8A150078)] = "Authentication failed. Authenticated account is not the desired account.",
        [unchecked((int)0x8A150079)] = "Repair command not found.",
        [unchecked((int)0x8A15007A)] = "Repair operation is not applicable.",
        [unchecked((int)0x8A15007B)] = "Repair operation failed.",
        [unchecked((int)0x8A15007C)] = "The installer technology in use doesn't support repair.",
        [unchecked((int)0x8A15007D)] = "Repair operations involving administrator privileges are not permitted on packages installed within the user scope.",
        [unchecked((int)0x8A15007E)] = "The SQLite connection was terminated to prevent corruption.",
        [unchecked((int)0x8A15007F)] = "Failed to get Microsoft Store package catalog.",
        [unchecked((int)0x8A150080)] = "No applicable Microsoft Store package found from Microsoft Store package catalog.",
        [unchecked((int)0x8A150081)] = "Failed to get Microsoft Store package download information.",
        [unchecked((int)0x8A150082)] = "No applicable Microsoft Store package found for download.",
        [unchecked((int)0x8A150083)] = "Failed to retrieve Microsoft Store package license.",
        [unchecked((int)0x8A150084)] = "The Microsoft Store package does not support download.",
        [unchecked((int)0x8A150085)] = "Failed to retrieve Microsoft Store package license. The Microsoft Entra Id account does not have required privilege.",
        [unchecked((int)0x8A150086)] = "Downloaded zero byte installer; ensure that your network connection is working properly.",
        [unchecked((int)0x8A150087)] = "Failed installing one or more fonts.",
        [unchecked((int)0x8A150088)] = "Font file is not supported and cannot be installed.",
        [unchecked((int)0x8A150089)] = "Font package is already installed.",
        [unchecked((int)0x8A15008A)] = "Font file not found.",
        [unchecked((int)0x8A15008B)] = "Font uninstall failed. The font may not be in a good state. Try uninstalling after a restart.",
        [unchecked((int)0x8A15008C)] = "Font validation failed.",
        [unchecked((int)0x8A15008D)] = "Font rollback failed. The font may not be in a good state. Try uninstalling after a restart.",
        [unchecked((int)0x8A15008E)] = "An upgrade is available but uses a different install technology than the current installation",
        [unchecked((int)0x8A150101)] = "Application is currently running. Exit the application then try again.",
        [unchecked((int)0x8A150102)] = "Another installation is already in progress. Try again later.",
        [unchecked((int)0x8A150103)] = "One or more file is being used. Exit the application then try again.",
        [unchecked((int)0x8A150104)] = "This package has a dependency missing from your system.",
        [unchecked((int)0x8A150105)] = "There's no more space on your PC. Make space, then try again.",
        [unchecked((int)0x8A150106)] = "There's not enough memory available to install. Close other applications then try again.",
        [unchecked((int)0x8A150107)] = "This application requires internet connectivity. Connect to a network then try again.",
        [unchecked((int)0x8A150108)] = "This application encountered an error during installation. Contact support.",
        [unchecked((int)0x8A150109)] = "Restart your PC to finish installation.",
        [unchecked((int)0x8A15010A)] = "Installation failed. Restart your PC then try again.",
        [unchecked((int)0x8A15010B)] = "Your PC will restart to finish installation.",
        [unchecked((int)0x8A15010C)] = "You cancelled the installation.",
        [unchecked((int)0x8A15010D)] = "Another version of this application is already installed.",
        [unchecked((int)0x8A15010E)] = "A higher version of this application is already installed.",
        [unchecked((int)0x8A15010F)] = "Organization policies are preventing installation. Contact your admin.",
        [unchecked((int)0x8A150110)] = "Failed to install package dependencies.",
        [unchecked((int)0x8A150111)] = "Application is currently in use by another application.",
        [unchecked((int)0x8A150112)] = "Invalid parameter.",
        [unchecked((int)0x8A150113)] = "Package not supported by the system.",
        [unchecked((int)0x8A150114)] = "The installer does not support upgrading an existing package.",
        [unchecked((int)0x8A150115)] = "Installation failed with a custom installer error.",
        [unchecked((int)0x8A150201)] = "The Apps and Features Entry for the package could not be found.",
        [unchecked((int)0x8A150203)] = "The install location could not be found.",
        [unchecked((int)0x8A150204)] = "The hash of the existing file did not match.",
        [unchecked((int)0x8A150205)] = "File not found.",
        [unchecked((int)0x8A150207)] = "The file could not be accessed.",
        [unchecked((int)0x8A15C001)] = "The configuration file is invalid.",
        [unchecked((int)0x8A15C002)] = "The YAML syntax is invalid.",
        [unchecked((int)0x8A15C003)] = "A configuration field has an invalid type.",
        [unchecked((int)0x8A15C004)] = "The configuration has an unknown version.",
        [unchecked((int)0x8A15C005)] = "An error occurred while applying the configuration.",
        [unchecked((int)0x8A15C006)] = "The configuration contains a duplicate identifier.",
        [unchecked((int)0x8A15C007)] = "The configuration is missing a dependency.",
        [unchecked((int)0x8A15C008)] = "The configuration has an unsatisfied dependency.",
        [unchecked((int)0x8A15C009)] = "An assertion for the configuration unit failed.",
        [unchecked((int)0x8A15C00A)] = "The configuration was manually skipped.",
        [unchecked((int)0x8A15C00B)] = "The user declined to continue execution.",
        [unchecked((int)0x8A15C00C)] = "The dependency graph contains a cycle which cannot be resolved.",
        [unchecked((int)0x8A15C00D)] = "The configuration has an invalid field value.",
        [unchecked((int)0x8A15C00E)] = "The configuration is missing a field.",
        [unchecked((int)0x8A15C00F)] = "Some of the configuration units failed while testing their state.",
        [unchecked((int)0x8A15C010)] = "Configuration state was not tested.",
        [unchecked((int)0x8A15C011)] = "The configuration unit failed getting its properties.",
        [unchecked((int)0x8A15C012)] = "The specified configuration could not be found.",
        [unchecked((int)0x8A15C013)] = "Parameter cannot be passed across integrity boundary.",
        [unchecked((int)0x8A15C101)] = "The configuration unit was not installed.",
        [unchecked((int)0x8A15C102)] = "The configuration unit could not be found.",
        [unchecked((int)0x8A15C103)] = "Multiple matches were found for the configuration unit; specify the module to select the correct one.",
        [unchecked((int)0x8A15C104)] = "The configuration unit failed while attempting to get the current system state.",
        [unchecked((int)0x8A15C105)] = "The configuration unit failed while attempting to test the current system state.",
        [unchecked((int)0x8A15C106)] = "The configuration unit failed while attempting to apply the desired state.",
        [unchecked((int)0x8A15C107)] = "The module for the configuration unit is available in multiple locations with the same version.",
        [unchecked((int)0x8A15C108)] = "Loading the module for the configuration unit failed.",
        [unchecked((int)0x8A15C109)] = "The configuration unit returned an unexpected result during execution.",
        [unchecked((int)0x8A15C110)] = "A unit contains a setting that requires the config root.",
        [unchecked((int)0x8A15C111)] = "Loading the module for the configuration unit failed because it requires administrator privileges to run.",
        [unchecked((int)0x8A15C112)] = "Operation is not supported by the configuration processor.",
    };

    // Synchronized from microsoft/winget-cli master:
    // Localization/Resources/it-IT/winget.resw
    private static readonly IReadOnlyDictionary<int, string> ItalianDescriptions = new Dictionary<int, string>
    {
        [unchecked((int)0x0A150202)] = "Il percorso di installazione non è applicabile.",
        [unchecked((int)0x0A150206)] = "Il file è stato trovato ma l'hash non è stato controllato.",
        [unchecked((int)0x8A150001)] = "Errore interno",
        [unchecked((int)0x8A150002)] = "Argomenti della riga di comando non validi",
        [unchecked((int)0x8A150003)] = "L'esecuzione del comando non è riuscita",
        [unchecked((int)0x8A150004)] = "Apertura del manifesto non riuscita",
        [unchecked((int)0x8A150005)] = "Segnale di annullamento ricevuto",
        [unchecked((int)0x8A150006)] = "L'esecuzione di ShellExecute non è riuscita",
        [unchecked((int)0x8A150007)] = "Impossibile elaborare il manifesto. La versione del manifesto è superiore a quella supportata. Aggiornare il client.",
        [unchecked((int)0x8A150008)] = "Download del programma di installazione non riuscito",
        [unchecked((int)0x8A150009)] = "Impossibile scrivere nell'indice; è una versione dello schema superiore",
        [unchecked((int)0x8A15000A)] = "L'indice è danneggiato",
        [unchecked((int)0x8A15000B)] = "Le informazioni di origine configurate sono danneggiate",
        [unchecked((int)0x8A15000C)] = "Il nome dell'origine è già configurato",
        [unchecked((int)0x8A15000D)] = "Il tipo di origine non è valido",
        [unchecked((int)0x8A15000E)] = "Il file MSIX è un bundle, non un pacchetto",
        [unchecked((int)0x8A15000F)] = "Mancano i dati richiesti dall'origine",
        [unchecked((int)0x8A150010)] = "Nessuno dei programmi di installazione è applicabile al sistema corrente",
        [unchecked((int)0x8A150011)] = "L'hash del file del programma di installazione non corrisponde al manifesto",
        [unchecked((int)0x8A150012)] = "Il nome di origine non esiste",
        [unchecked((int)0x8A150013)] = "Il percorso di origine è già configurato con un altro nome",
        [unchecked((int)0x8A150014)] = "Nessun pacchetto trovato",
        [unchecked((int)0x8A150015)] = "Nessuna origine configurata",
        [unchecked((int)0x8A150016)] = "Sono stati trovati più pacchetti corrispondenti ai criteri",
        [unchecked((int)0x8A150017)] = "Nessun manifesto trovato corrispondente ai criteri",
        [unchecked((int)0x8A150018)] = "Non è stato possibile ottenere la cartella pubblica dal pacchetto di origine",
        [unchecked((int)0x8A150019)] = "Il comando richiede i privilegi di amministratore per essere eseguito",
        [unchecked((int)0x8A15001A)] = "Il percorso di origine non è sicuro",
        [unchecked((int)0x8A15001B)] = "Il client Microsoft Store è bloccato dai criteri",
        [unchecked((int)0x8A15001C)] = "L'applicazione Microsoft Store è bloccata dai criteri",
        [unchecked((int)0x8A15001D)] = "La funzionalità è attualmente in fase di sviluppo. Può essere abilitato con le impostazioni di WinGet.",
        [unchecked((int)0x8A15001E)] = "Non è stato possibile installare l'app Microsoft Store",
        [unchecked((int)0x8A15001F)] = "Non è stato possibile eseguire il completamento automatico",
        [unchecked((int)0x8A150020)] = "Non è stato possibile inizializzare il parser YAML",
        [unchecked((int)0x8A150021)] = "È stata rilevata una chiave YAML non valida",
        [unchecked((int)0x8A150022)] = "È stata rilevata una chiave YAML duplicata",
        [unchecked((int)0x8A150023)] = "Operazione YAML non valida",
        [unchecked((int)0x8A150024)] = "Non è stato possibile compilare il documento YAML",
        [unchecked((int)0x8A150025)] = "Stato dell'emettitore YAML non valido",
        [unchecked((int)0x8A150026)] = "Dati YAML non validi",
        [unchecked((int)0x8A150027)] = "Errore LibYAML",
        [unchecked((int)0x8A150028)] = "Convalida del manifesto riuscita con avviso",
        [unchecked((int)0x8A150029)] = "Convalida del manifesto non riuscita",
        [unchecked((int)0x8A15002A)] = "Il manifesto non è valido",
        [unchecked((int)0x8A15002B)] = "Non è stato trovato alcun aggiornamento applicabile",
        [unchecked((int)0x8A15002C)] = "aggiornamento di winget -- tutto completato con errori",
        [unchecked((int)0x8A15002D)] = "Non è stato possibile eseguire il controllo di sicurezza per il programma di installazione",
        [unchecked((int)0x8A15002E)] = "La dimensione del download non corrisponde alla lunghezza prevista del contenuto",
        [unchecked((int)0x8A15002F)] = "Comando di disinstallazione non trovato",
        [unchecked((int)0x8A150030)] = "L'esecuzione del comando di disinstallazione non è riuscita",
        [unchecked((int)0x8A150031)] = "Errore iteratore di interruzione dell'ICU",
        [unchecked((int)0x8A150032)] = "Errore casemap ICU",
        [unchecked((int)0x8A150033)] = "Errore regex ICU",
        [unchecked((int)0x8A150034)] = "Non è stato possibile installare uno o più pacchetti importati",
        [unchecked((int)0x8A150035)] = "Non è stato possibile trovare uno o più pacchetti richiesti",
        [unchecked((int)0x8A150036)] = "Il file Json non è valido",
        [unchecked((int)0x8A150037)] = "Il percorso di origine non è remoto",
        [unchecked((int)0x8A150038)] = "L'origine rest configurata non è supportata",
        [unchecked((int)0x8A150039)] = "Dati non validi restituiti dall'origine rest",
        [unchecked((int)0x8A15003A)] = "L'operazione è bloccata da Criteri di gruppo",
        [unchecked((int)0x8A15003B)] = "Errore interno dell'API Rest",
        [unchecked((int)0x8A15003C)] = "L'URL dell'origine rest non è valido",
        [unchecked((int)0x8A15003D)] = "Tipo MIME non supportato restituito dall'API REST",
        [unchecked((int)0x8A15003E)] = "Versione del contratto di origine rest non valida",
        [unchecked((int)0x8A15003F)] = "I dati di origine sono danneggiati o manomessi",
        [unchecked((int)0x8A150040)] = "Errore nella lettura del flusso",
        [unchecked((int)0x8A150041)] = "I contratti del pacchetto non sono stati concordati",
        [unchecked((int)0x8A150042)] = "Errore durante la lettura dell'input nel prompt",
        [unchecked((int)0x8A150043)] = "La richiesta di ricerca non è supportata da una o più origini",
        [unchecked((int)0x8A150044)] = "L'endpoint dell'API REST non è stato trovato.",
        [unchecked((int)0x8A150045)] = "Impossibile aprire l'origine.",
        [unchecked((int)0x8A150046)] = "Contratti di origine non accettati",
        [unchecked((int)0x8A150047)] = "Le dimensioni dell'intestazione superano il limite consentito di 1024 caratteri. Ridurre le dimensioni e riprovare.",
        [unchecked((int)0x8A150048)] = "File di risorse mancante",
        [unchecked((int)0x8A150049)] = "L'esecuzione dell'installazione MSI non è riuscita",
        [unchecked((int)0x8A15004A)] = "Gli argomenti per msiexec non sono validi",
        [unchecked((int)0x8A15004B)] = "Non è stato possibile aprire una o più origini",
        [unchecked((int)0x8A15004C)] = "Non è stato possibile convalidare le dipendenze",
        [unchecked((int)0x8A15004D)] = "Uno o più pacchetti mancanti",
        [unchecked((int)0x8A15004E)] = "Colonna tabella non valida",
        [unchecked((int)0x8A15004F)] = "La versione di aggiornamento non è più recente della versione installata",
        [unchecked((int)0x8A150050)] = "La versione dell'aggiornamento è sconosciuta e l'override non è specificato",
        [unchecked((int)0x8A150051)] = "Errore di conversione ICU",
        [unchecked((int)0x8A150052)] = "Non è stato possibile installare il pacchetto portabile",
        [unchecked((int)0x8A150053)] = "Il volume non supporta i punti di reparse",
        [unchecked((int)0x8A150054)] = "Esiste già un pacchetto portabile di un'origine diversa.",
        [unchecked((int)0x8A150055)] = "Impossibile creare il collegamento simbolico. Il percorso punta a una directory.",
        [unchecked((int)0x8A150056)] = "Impossibile eseguire il programma di installazione da un contesto di amministratore.",
        [unchecked((int)0x8A150057)] = "Non è stato possibile disinstallare il pacchetto portabile",
        [unchecked((int)0x8A150058)] = "Non è stato possibile convalidare i valori DisplayVersion rispetto all'indice.",
        [unchecked((int)0x8A150059)] = "Uno o più argomenti non sono supportati.",
        [unchecked((int)0x8A15005A)] = "I caratteri null incorporati non sono consentiti in SQLite",
        [unchecked((int)0x8A15005B)] = "Impossibile trovare il programma di installazione annidato nell'archivio.",
        [unchecked((int)0x8A15005C)] = "Impossibile estrarre l'archivio.",
        [unchecked((int)0x8A15005D)] = "È stato specificato un percorso di file relativo non valido per il programma di installazione annidato.",
        [unchecked((int)0x8A15005E)] = "Il certificato del server non corrisponde ad alcun valore previsto.",
        [unchecked((int)0x8A15005F)] = "È necessario specificare il percorso di installazione.",
        [unchecked((int)0x8A150060)] = "L'analisi del malware dell'archivio non è riuscita.",
        [unchecked((int)0x8A150061)] = "È stata trovata almeno una versione del pacchetto installato.",
        [unchecked((int)0x8A150062)] = "Esiste già un pin per il pacchetto.",
        [unchecked((int)0x8A150063)] = "Nessun pin per il pacchetto.",
        [unchecked((int)0x8A150064)] = "Impossibile aprire il database dei pin.",
        [unchecked((int)0x8A150065)] = "Installazione di una o più applicazioni non riuscita",
        [unchecked((int)0x8A150066)] = "Non è stato possibile disinstallare una o più applicazioni",
        [unchecked((int)0x8A150067)] = "Una o più query non hanno restituito esattamente una corrispondenza",
        [unchecked((int)0x8A150068)] = "Il pacchetto contiene un PIN che impedisce l'aggiornamento.",
        [unchecked((int)0x8A150069)] = "Il pacchetto attualmente installato è il pacchetto stub",
        [unchecked((int)0x8A15006A)] = "Segnale di arresto dell'applicazione ricevuto",
        [unchecked((int)0x8A15006B)] = "Non è stato possibile scaricare le dipendenze del pacchetto.",
        [unchecked((int)0x8A15006C)] = "Non è stato possibile scaricare il pacchetto. Il download per l'installazione offline non è consentito.",
        [unchecked((int)0x8A15006D)] = "Un servizio richiesto è occupato o non disponibile. Riprova più tardi.",
        [unchecked((int)0x8A15006E)] = "Il GUID specificato non corrisponde a uno stato di ripresa valido.",
        [unchecked((int)0x8A15006F)] = "La versione corrente del client non corrisponde alla versione client dello stato salvato.",
        [unchecked((int)0x8A150070)] = "I dati sullo stato di ripresa non sono validi.",
        [unchecked((int)0x8A150071)] = "Impossibile aprire il database del checkpoint.",
        [unchecked((int)0x8A150072)] = "È stato superato il limite massimo di ripresa.",
        [unchecked((int)0x8A150073)] = "Informazioni di autenticazione non valide.",
        [unchecked((int)0x8A150074)] = "Metodo di autenticazione non supportato.",
        [unchecked((int)0x8A150075)] = "Autenticazione non riuscita.",
        [unchecked((int)0x8A150076)] = "Impossibile eseguire l'autenticazione. È richiesta l'autenticazione interattiva.",
        [unchecked((int)0x8A150077)] = "Impossibile eseguire l'autenticazione. Annullato dall'utente.",
        [unchecked((int)0x8A150078)] = "Autenticazione non riuscita. L'account autenticato non è l'account desiderato.",
        [unchecked((int)0x8A150079)] = "Comando di ripristino non trovato.",
        [unchecked((int)0x8A15007A)] = "L'operazione di ripristino non è applicabile.",
        [unchecked((int)0x8A15007B)] = "L'operazione di ripristino non è riuscita.",
        [unchecked((int)0x8A15007C)] = "La tecnologia del programma di installazione in uso non supporta il ripristino.",
        [unchecked((int)0x8A15007D)] = "Le operazioni di ripristino che richiedono privilegi di amministratore non sono consentite nei pacchetti installati nell'ambito utente.",
        [unchecked((int)0x8A15007E)] = "La connessione SQLite è stata terminata per evitare il danneggiamento.",
        [unchecked((int)0x8A15007F)] = "Non è possibile ottenere il catalogo pacchetti Microsoft Store.",
        [unchecked((int)0x8A150080)] = "Non sono stati trovati pacchetti Microsoft Store applicabili dal catalogo pacchetti Microsoft Store.",
        [unchecked((int)0x8A150081)] = "Non è possibile ottenere informazioni sul download del pacchetto Microsoft Store.",
        [unchecked((int)0x8A150082)] = "Non sono stati trovati pacchetti Microsoft Store applicabili per il download.",
        [unchecked((int)0x8A150083)] = "Non è stato possibile recuperare la licenza del pacchetto Microsoft Store.",
        [unchecked((int)0x8A150084)] = "Il pacchetto Microsoft Store non supporta il download.",
        [unchecked((int)0x8A150085)] = "Non è stato possibile recuperare Microsoft Store licenza del pacchetto. L'account id Microsoft Entra non dispone dei privilegi necessari.",
        [unchecked((int)0x8A150086)] = "Programma di installazione a zero byte scaricato; verificare che la connessione di rete funzioni correttamente.",
        [unchecked((int)0x8A150087)] = "Impossibile installare uno o più tipi di carattere.",
        [unchecked((int)0x8A150088)] = "Il file dei tipi di carattere non è supportato e non può essere installato.",
        [unchecked((int)0x8A150089)] = "Il pacchetto di tipi di carattere è già installato.",
        [unchecked((int)0x8A15008A)] = "Il file del tipo di carattere non è stato trovato.",
        [unchecked((int)0x8A15008B)] = "Disinstallazione del carattere non riuscita. Il tipo di carattere potrebbe non essere in uno stato valido. Provare a disinstallare dopo un riavvio.",
        [unchecked((int)0x8A15008C)] = "Convalida del tipo di carattere non riuscita.",
        [unchecked((int)0x8A15008D)] = "Rollback del tipo di carattere non riuscito. Il tipo di carattere potrebbe non essere in uno stato valido. Provare a disinstallare dopo un riavvio.",
        [unchecked((int)0x8A150101)] = "L'applicazione è attualmente in esecuzione. Uscire dall'applicazione, quindi riprovare.",
        [unchecked((int)0x8A150102)] = "È già in corso un'altra installazione. Riprova più tardi.",
        [unchecked((int)0x8A150103)] = "È in uso uno o più file. Uscire dall'applicazione, quindi riprovare.",
        [unchecked((int)0x8A150104)] = "Nel sistema manca una dipendenza per questo pacchetto.",
        [unchecked((int)0x8A150105)] = "Non c'è più spazio nel PC. Liberare spazio, quindi riprovare.",
        [unchecked((int)0x8A150106)] = "Memoria insufficiente per l'installazione. Chiudi le altre applicazioni, quindi riprova.",
        [unchecked((int)0x8A150107)] = "Questa applicazione richiede la connettività Internet. Connettiti a una rete e riprova.",
        [unchecked((int)0x8A150108)] = "Errore dell'applicazione durante l'installazione. Contattare il supporto tecnico.",
        [unchecked((int)0x8A150109)] = "Riavvia il PC per completare l'installazione..",
        [unchecked((int)0x8A15010A)] = "Installazione non riuscita. Riavvia il PC e riprova.",
        [unchecked((int)0x8A15010B)] = "Il PC verrà riavviato per completare l'installazione.",
        [unchecked((int)0x8A15010C)] = "Hai annullato l’installazione.",
        [unchecked((int)0x8A15010D)] = "È già installata un'altra versione di questa applicazione.",
        [unchecked((int)0x8A15010E)] = "È già installata una versione successiva di questa applicazione.",
        [unchecked((int)0x8A15010F)] = "I criteri dell'organizzazione impediscono l'installazione. Contattare l'amministratore.",
        [unchecked((int)0x8A150110)] = "Non è stato possibile installare le dipendenze del pacchetto.",
        [unchecked((int)0x8A150111)] = "L'applicazione è attualmente utilizzata da un'altra applicazione.",
        [unchecked((int)0x8A150112)] = "Parametro non valido.",
        [unchecked((int)0x8A150113)] = "Pacchetto non supportato dal sistema.",
        [unchecked((int)0x8A150114)] = "Il programma di installazione non supporta l'aggiornamento di un pacchetto esistente.",
        [unchecked((int)0x8A150115)] = "Installazione non riuscita a causa di un errore del programma di installazione personalizzato.",
        [unchecked((int)0x8A150201)] = "La voce App e funzionalità per il pacchetto non è stata trovata.",
        [unchecked((int)0x8A150203)] = "Il percorso di installazione non è stato trovato.",
        [unchecked((int)0x8A150204)] = "L'hash del file esistente non corrisponde.",
        [unchecked((int)0x8A150205)] = "File non trovato.",
        [unchecked((int)0x8A150207)] = "Impossibile accedere al file.",
        [unchecked((int)0x8A15C001)] = "Il file di configurazione non è valido.",
        [unchecked((int)0x8A15C002)] = "Sintassi YAML non valida.",
        [unchecked((int)0x8A15C003)] = "Un campo di configurazione ha un tipo non valido.",
        [unchecked((int)0x8A15C004)] = "La versione della configurazione è sconosciuta.",
        [unchecked((int)0x8A15C005)] = "Errore durante l'applicazione della configurazione.",
        [unchecked((int)0x8A15C006)] = "La configurazione contiene un identificatore duplicato.",
        [unchecked((int)0x8A15C007)] = "Nella configurazione manca una dipendenza.",
        [unchecked((int)0x8A15C008)] = "La configurazione ha una dipendenza non soddisfatta.",
        [unchecked((int)0x8A15C009)] = "Un'asserzione per l'unità di configurazione non è riuscita.",
        [unchecked((int)0x8A15C00A)] = "La configurazione è stata ignorata manualmente.",
        [unchecked((int)0x8A15C00B)] = "L'utente ha rifiutato di continuare l'esecuzione.",
        [unchecked((int)0x8A15C00C)] = "Il grafico delle dipendenze contiene un ciclo che non può essere risolto.",
        [unchecked((int)0x8A15C00D)] = "La configurazione contiene un valore di campo non valido.",
        [unchecked((int)0x8A15C00E)] = "Nella configurazione manca un campo.",
        [unchecked((int)0x8A15C00F)] = "Errore di alcune unità di configurazione durante il test dello stato.",
        [unchecked((int)0x8A15C010)] = "Lo stato della configurazione non è stato testato.",
        [unchecked((int)0x8A15C011)] = "Non è possibile ottenere le proprietà dell'unità di configurazione.",
        [unchecked((int)0x8A15C012)] = "Non è possibile trovare la configurazione specificata.",
        [unchecked((int)0x8A15C013)] = "Il parametro non può essere passato oltre il limite di integrità.",
        [unchecked((int)0x8A15C101)] = "L'unità di configurazione non è stata installata.",
        [unchecked((int)0x8A15C102)] = "Impossibile trovare l'unità di configurazione.",
        [unchecked((int)0x8A15C103)] = "Sono state trovate più corrispondenze per l'unità di configurazione; specificare il modulo per selezionare quello corretto.",
        [unchecked((int)0x8A15C104)] = "Errore dell'unità di configurazione durante il tentativo di ottenere lo stato corrente del sistema.",
        [unchecked((int)0x8A15C105)] = "Errore dell'unità di configurazione durante il tentativo di testare lo stato corrente del sistema.",
        [unchecked((int)0x8A15C106)] = "Errore dell'unità di configurazione durante il tentativo di applicare lo stato desiderato.",
        [unchecked((int)0x8A15C107)] = "Il modulo per l'unità di configurazione è disponibile in più località con la stessa versione.",
        [unchecked((int)0x8A15C108)] = "Caricamento del modulo per l'unità di configurazione non riuscito.",
        [unchecked((int)0x8A15C109)] = "L'unità di configurazione ha restituito un risultato imprevisto durante l'esecuzione.",
        [unchecked((int)0x8A15C110)] = "Un'unità contiene un'impostazione che richiede la radice di configurazione.",
        [unchecked((int)0x8A15C111)] = "Il caricamento del modulo per l'unità di configurazione non è riuscito perché richiede privilegi di amministratore per l'esecuzione.",
        [unchecked((int)0x8A15C112)] = "Operazione non supportata dal processore di configurazione.",
    };

    public static bool TryGetSymbol(int exitCode, out string symbol) => Symbols.TryGetValue(exitCode, out symbol!);

    public static bool TryGetDescription(int exitCode, string? localeCode, out string description)
    {
        var descriptions = !string.IsNullOrWhiteSpace(localeCode)
            && localeCode.StartsWith("it", StringComparison.OrdinalIgnoreCase)
                ? ItalianDescriptions
                : EnglishDescriptions;

        if (descriptions.TryGetValue(exitCode, out description!))
        {
            return true;
        }

        if (!ReferenceEquals(descriptions, EnglishDescriptions) && EnglishDescriptions.TryGetValue(exitCode, out description!))
        {
            return true;
        }

        description = string.Empty;
        return false;
    }

    public static bool TryGetLabel(int exitCode, out string label)
    {
        if (!TryGetSymbol(exitCode, out var symbol))
        {
            label = string.Empty;
            return false;
        }

        label = FormatSymbolLabel(symbol);
        return true;
    }

    public static string FormatHex(int exitCode) => $"0x{unchecked((uint)exitCode):X8}";

    private static string FormatSymbolLabel(string symbol)
    {
        var cleaned = symbol
            .Replace("APPINSTALLER_CLI_ERROR_", string.Empty, StringComparison.Ordinal)
            .Replace("WINGET_INSTALLED_STATUS_", string.Empty, StringComparison.Ordinal)
            .Replace("WINGET_CONFIG_ERROR_", string.Empty, StringComparison.Ordinal);
        var textInfo = CultureInfo.InvariantCulture.TextInfo;
        return textInfo.ToTitleCase(cleaned.Replace('_', ' ').ToLowerInvariant());
    }

    public static int Count => Symbols.Count;

    public static bool ContainsDuplicateCodes => Symbols.Count != Symbols.Keys.Distinct().Count();
}
